"""adding pass fiel


Revision ID: d35377ae3731
Revises: 8560a78360d1
Create Date: 2025-10-04 23:21:36.901671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35377ae3731'
down_revision = '8560a78360d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userss', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
